/*
 * TA-GM模块
 * TA-GM API接口
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: robin.li@trustasia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trustasia.tagm.api;

import com.trustasia.tagm.core.ApiClient;
import com.trustasia.tagm.core.ApiException;
import com.trustasia.tagm.model.apitest.ResponseResultTestVO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for TestApi
 */
@Disabled
public class TestApiTest {

    private final TestApi api = new TestApi();

    /**
     * 获取基本信息
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInfoTest() throws ApiException {
        Object name = null;
        Object age = null;
        ApiClient apiClient = new ApiClient();
        apiClient.setKeyManagers(null);


        ResponseResultTestVO response = api.getInfo(name, age);
        // TODO: test validations
    }

}
