/*
 * TA-GM模块
 * TA-GM API接口
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * Contact: robin.li@trustasia.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.trustasia.tagm.model.apitest;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TestVO
 */
public class TestVOTest {
    private final TestVO model = new TestVO();

    /**
     * Model tests for TestVO
     */
    @Test
    public void testTestVO() {
        // TODO: test TestVO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
